language: node_js
node_js:
  - "stable"
services:
  - docker
# Pre-testing installs
install:
  - echo "nothing needs to be installed"
matrix:
  fast_finish: true
  include:
    - env: TypeScript
      before_script:
        - cd udagram-api-user
  	- echo "no tests"
      script:
  	- docker --version # print the version for logging
  	- docker build -t udagram-api-user .
  	- docker tag simple-node benyusouf/udagram-api-user:latest
      after_success:
  	- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  	- docker push benyusouf/udagram-api-user
      before_script:
        - cd udagram-api-feed
  	- echo "no tests"
      script:
  	- docker --version # print the version for logging
  	- docker build -t udagram-api-feed .
  	- docker tag simple-node benyusouf/udagram-api-feed:latest
      after_success:
  	- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  	- docker push benyusouf/udagram-api-feed
on:
  branch: master
