language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t udagram-api-user -f udagram-api-user/Dockerfile .
  - docker tag udagram-api-user benyusouf/udagram-api-user:latest
  - docker build -t udagram-api-feed -f udagram-api-feed/Dockerfile .
  - docker tag udagram-api-feed benyusouf/udagram-api-feed:latest
  - docker build -t udagram-front-end -f udagram-frontend/Dockerfile .
  - docker tag udagram-front-end benyusouf/udagram-front-end:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push benyusouf/udagram-api-user
  - docker push benyusouf/udagram-api-feed
  - docker push benyusouf/udagram-front-end
