language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - cd udagram-api-user
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -f udagram-api-user/DockerFile
  - docker tag udagram-api-user benyusouf/udagram-api-user:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push benyusouf/udagram-api-user

before_script:
  - cd udagram-api-feed
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -f udagram-api-feed/DockerFile
  - docker tag udagram-api-feed benyusouf/udagram-api-feed:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push benyusouf/udagram-api-feed 
