language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - "cd udagram-api-user"
  - docker build -t benyusouf/udagram-api-user .
  - docker tag benyusouf/udagram-api-user benyusouf/udagram-api-user:latest
  - "cd .."
  - "cd udagram-api-feed"
  - docker build -t benyusouf/udagram-api-feed .
  - docker tag benyusouf/udagram-api-feed benyusouf/udagram-api-feed:latest
  - "cd .."
  - "cd udagram-frontend"
  - docker build -t benyusouf/udagram-front-end .
  - docker tag benyusouf/udagram-front-end benyusouf/udagram-front-end:latest
  - "cd .."
  - "cd reverse-proxy"
  - docker build -t benyusouf/reverse-proxy .
  - docker tag benyusouf/reverse-proxy benyusouf/reverse-proxy:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push benyusouf/udagram-api-user
  - docker push benyusouf/udagram-api-feed
  - docker push benyusouf/udagram-front-end
  - docker push benyusouf/reverse-proxy
