apiVersion: v1
kind: Service
metadata:
    labels:
        service: reverse-proxy
    name: reverse-proxy
spec:
    ports:
    - name: "8380"
      port: 8380
      targetPort: 8380
    selector:
      service: reverse-proxy
    type: LoadBalancer